import { createContext, useContext, ReactNode, useEffect, useState } from 'react';

export type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  isRTL: boolean;
  t: (key: string, params?: Record<string, string | number>) => string;
  dir: 'rtl' | 'ltr';
  textAlign: (align: 'left' | 'right' | 'center') => string;
  flexDirection: (direction?: 'row' | 'col') => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  ar: {
    // Navigation
    home: 'الرئيسية',
    aboutUs: 'من نحن',
    aboutTitle: 'عن رينبو ترافل',
    services: 'الخدمات',
    offers: 'العروض',
    contact: 'اتصل بنا',
    loginSignup: 'تسجيل الدخول / إنشاء حساب',

    // Search
    searchPlaceholder: 'البحث عن الوجهات، الخدمات، العروض...',
    searchDestinations: 'البحث عن الوجهات...',

    // Hero sections
    welcome: 'مرحباً بكم في رينبو ترافل',
    exploreWorld: 'استكشف العالم معنا',
    journeyBegins: 'الرحلة تبدأ معنا...',
    memoriesYours: 'والذكريات لكم',
    yourTrustedPartner: 'شريككم الموثوق في نابلس، نقدم حلول سفر كاملة وتجارب لا تُنسى حول العالم.',
    discoverDestinations: 'اكتشف وجهات مذهلة',
    topDestinations: 'أفضل وجهات السفر',
    explorePopular: 'استكشف أكثر الدول شعبية التي يحبها الناس زيارتها',
    ourServices: 'خدماتنا',
    completeSolutions: 'حلول سفر كاملة مصممة حسب احتياجاتك. من الحجز إلى التخطيط، نحن نوفر لك كل شيء.',
    specialOffers: 'عروض خاصة',
    offersPageDesc: 'اكتشف عروض سفر رائعة وحزم حصرية لوجهات أحلامك',
    exclusiveDeals: 'عروض حصرية وحزم لتجارب لا تُنسى',
    quickLinks: 'روابط سريعة',
    contactUs: 'اتصل بنا',
    getInTouch: 'نحن هنا لمساعدتك في تخطيط رحلتك المثالية. تواصل معنا اليوم!',

    // Buttons and actions
    getStarted: 'ابدأ الآن',
    learnMore: 'اعرف المزيد',
    bookNow: 'احجز الآن',
    viewDetails: 'عرض التفاصيل',
    sendMessage: 'إرسال الرسالة',
    sending: 'جارٍ الإرسال...',
    submit: 'إرسال',

    // Forms
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    message: 'الرسالة',
    name: 'الاسم',

    // Services
    flightBooking: 'حجز الطيران',
    flightDesc: 'احجز رحلات طيران إلى وجهات حول العالم بأسعار تنافسية وخيارات مرنة.',
    hotelReservations: 'حجز الفنادق',
    hotelDesc: 'اعثر واحجز الإقامة المثالية لرحلتك.',
    tourPackages: 'حزم الجولات',
    tourDesc: 'استكشف حزم الجولات المصممة بعناية والتي تشمل الطيران والفنادق والجولات والأنشطة.',
    visaAssistance: 'مساعدة التأشيرات',
    visaDesc: 'احصل على مساعدة متخصصة في طلبات التأشيرات والوثائق.',
    travelPlanning: 'تخطيط السفر',
    planningDesc: 'دع مستشاري السفر ذوي الخبرة يساعدونك في تخطيط رحلتك المثالية.',

    // Features
    internationalFlights: 'رحلات دولية ومحلية',
    bestFare: 'ضمان أفضل سعر',
    easyCancellation: 'إلغاء وإعادة جدولة سهلة',
    customerSupport: 'دعم العملاء 24/7',
    wideAccommodations: 'مجموعة واسعة من الإقامات',
    bestPrice: 'ضمان أفضل سعر',
    verifiedReviews: 'تقييمات ومراجعات موثقة',
    groupRates: 'أسعار خاصة للمجموعات',
    allInclusive: 'حزم شاملة',
    customizable: 'جداول زمنية قابلة للتخصيص',
    localGuides: 'مرشدون محليون متخصصون',
    privateTours: 'جولات جماعية وخاصة',
    visaConsultation: 'استشارات التأشيرات',
    documentPrep: 'إعداد الوثائق',
    applicationTracking: 'تتبع الطلبات',
    multipleCountries: 'دعم دول متعددة',
    personalized: 'جداول زمنية مخصصة',
    budgetPlanning: 'تخطيط الميزانية',
    activityRecs: 'توصيات الأنشطة',
    travelInsurance: 'خيارات التأمين على السفر',

    // Contact
    contactTitle: 'تواصل معنا',
    questionsHelp: 'لديك أسئلة أو تحتاج مساعدة؟ نحن هنا للمساعدة!',
    officeLocation: 'موقع المكتب',
    nablusCenter: 'مركز مدينة نابلس، الطابق الثاني، نابلس، فلسطين',
    phoneNumber: 'رقم الهاتف',
    available247: 'متوفر 24/7 للاستفسارات',
    emailAddress: 'البريد الإلكتروني',
    respond24h: 'سنرد خلال 24 ساعة',
    followUs: 'تابعنا على وسائل التواصل الاجتماعي',

    // Footer
    allRightsReserved: 'جميع الحقوق محفوظة.',
    rainbowTravel: 'رينبو ترافل والسياحة',

    // Booking
    bookingForm: 'احجز رحلتك',
    selectService: 'اختر الخدمة',
    selectDestination: 'اختر الوجهة',
    selectDate: 'اختر التاريخ',
    numberOfTravelers: 'عدد المسافرين',
    specialRequests: 'طلبات خاصة',
    passportType: 'نوع الجواز',
    palestinian: 'فلسطيني',
    other: 'أخرى',

    // About
    ourStory: 'قصتنا',
    storyText: 'مع أكثر من 15 عاماً من الخبرة في صناعة السفر، كانت رينبو ترافل شريككم الموثوق للرحلات التي لا تُنسى. نحن متخصصون في تقديم حلول سفر شاملة مصممة حسب احتياجاتكم.',
    ourValues: 'قيمنا',
    whyChoose: 'لماذا تختار رينبو ترافل؟',
    ourMission: 'رسالتنا',
    ourVision: 'رؤيتنا',
    competitivePrices: 'أسعار تنافسية',
    pricesDesc: 'نقدم أفضل قيمة مقابل أموالكم مع عروض حصرية وأسعار تنافسية على جميع حزمنا.',
    excellentService: 'خدمة ممتازة',
    serviceDesc: 'فريقنا المهني والودود ملتزم بتقديم خدمة عملاء استثنائية في كل خطوة.',
    organizedTrips: 'رحلات منظمة',
    organizedDesc: 'يتم التخطيط والتنظيم لكل التفاصيل بعناية لضمان أن تكون رحلتكم سلسة وآمنة وخالية من التوتر.',
    continuousOffers: 'عروض مستمرة',
    offersDesc: 'نحدث عروضنا باستمرار لنقدم لكم أفضل الصفقات وأحدث الوجهات.',

    // Auth
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    createAccount: 'إنشاء حساب',
    emailRequired: 'البريد الإلكتروني مطلوب',
    passwordRequired: 'كلمة المرور مطلوبة',
    nameRequired: 'الاسم مطلوب',
    passwordsNotMatch: 'كلمات المرور غير متطابقة',
    invalidEmail: 'البريد الإلكتروني غير صحيح',
    passwordTooShort: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    loginSuccess: 'تم تسجيل الدخول بنجاح',
    signupSuccess: 'تم إنشاء الحساب بنجاح',
    loginError: 'فشل في تسجيل الدخول',
    signupError: 'فشل في إنشاء الحساب',
    loading: 'جارٍ التحميل...',
    error: 'خطأ',
    success: 'نجح',
    close: 'إغلاق',
    yes: 'نعم',
    no: 'لا',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    view: 'عرض',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    page: 'صفحة',
    of: 'من',
    contactToday: 'تواصل معنا اليوم ودعنا نساعدك في تخطيط عطلتك المثالية',
    readyToBook: 'جاهز لحجز رحلتك؟',
    contactCustom: 'تواصل معنا وسننشئ حزمة مخصصة لك فقط',
    cantFind: 'لا تجد ما تبحث عنه؟',
    'Showing {count} destinations matching your search': 'عرض {count} وجهة تتطابق مع بحثك',
    'View All Offers': 'عرض جميع العروض',
    'What Our Customers Say': 'ماذا يقول عملاؤنا',
    'Real experiences from happy travelers': 'تجارب حقيقية من مسافرين سعداء',
    'Ready to Start Your Journey?': 'هل أنت مستعد لبدء رحلتك؟',
    'Book your dream vacation today and create memories that last a lifetime': 'احجز عطلتك المثالية اليوم واصنع ذكريات تدوم مدى الحياة',
    'Contact Us': 'اتصل بنا',
    'Follow Us': 'تابعنا',
    'Rainbow Travel & Tourism': 'رينبو ترافل والسياحة',
    'All rights reserved.': 'جميع الحقوق محفوظة.',
    'Have questions or need assistance? We are here to help! Reach out to us through any of the following channels.': 'هل لديك أسئلة أو تحتاج مساعدة؟ نحن هنا للمساعدة! تواصل معنا عبر أي من القنوات التالية.',
    'Find Us on the Map': 'اعثر علينا على الخريطة',
    'Visit our office at Nablus City Center': 'قم بزيارة مكتبنا في مركز مدينة نابلس',
    'Office Hours': 'ساعات العمل',
    'Sunday - Thursday': 'الأحد - الخميس',
    'Saturday': 'السبت',
    'Emergency support available 24/7 by phone': 'دعم الطوارئ متاح على مدار الساعة عبر الهاتف',
    'Get in Touch': 'تواصل معنا',
    'Send Us a Message': 'أرسل لنا رسالة',
    'Message Sent Successfully!': 'تم إرسال الرسالة بنجاح!',
    'Thank you for contacting us. We will get back to you within 24 hours.': 'شكراً لتواصلك معنا. سنرد خلال 24 ساعة.',
    'Enter your email': 'أدخل بريدك الإلكتروني',
    // About page specific
    ourMissionText: 'تقديم تجارب سفر استثنائية من خلال تقديم حلول سفر شاملة وموثوقة وبأسعار معقولة. نسعى لجعل كل رحلة سلسة ولا تُنسى، مما يضمن عودة عملائنا إلى منازلهم بقصص تستحق المشاركة وذكريات يحتفظون بها إلى الأبد.',
    ourVisionText: 'أن نصبح الوكالة الرائدة في السفر في فلسطين، معروفة بالتزامنا بالتميز والابتكار ورضا العملاء. نتخيل مستقبلاً يكون فيه السفر متاحاً للجميع، وتكون رينبو ترافل الخيار الأول للمسافرين الذين يبحثون عن الجودة والقيمة.',
    whyChooseDesc: 'نحن أكثر من مجرد وكالة سفر - نحن شركاؤك في المغامرة',
    ourCoreValues: 'قيمنا الأساسية',
    loadingServices: 'جارٍ تحميل الخدمات...',
    whyChooseRainbow: 'لماذا تختار رينبو ترافل؟',
    committedToExceptional: 'نحن ملتزمون بتقديم تجارب سفر استثنائية',
    bestValueMoney: 'نقدم أفضل قيمة مقابل أموالكم مع عروض حصرية وأسعار تنافسية.',
    professionalSupport: 'فريقنا المهني والودود ملتزم بتقديم خدمة عملاء استثنائية.',
    wellPlannedItineraries: 'يتم التخطيط والتنظيم لكل التفاصيل بعناية لضمان أن تكون رحلتكم سلسة وآمنة وخالية من التوتر.',
    regularPromotions: 'نحدث عروضنا باستمرار لنقدم لكم أفضل الصفقات وأحدث الوجهات.',
    filterByCountry: 'تصفية حسب البلد',
    allCountries: 'جميع البلدان',
    filterByPrice: 'تصفية حسب السعر',
    allPrices: 'جميع الأسعار',
    under700: 'أقل من 700 دولار',
    between700And1000: '700 - 1000 دولار',
    over1000: 'أكثر من 1000 دولار',
    showingResults: 'عرض {count} نتيجة{plural} لبحثك',
    loadingOffers: 'جارٍ تحميل العروض...',
    reviews: 'تقييمات',
    packageIncludes: 'تشمل الحزمة',
    highlights: 'النقاط البارزة',
    exploreDestinations: 'استكشف الوجهات',
    popularTouristAttractions: 'المعالم السياحية الشهيرة',
    discoverBeachesLandmarks: 'اكتشف الشواطئ الجميلة والمعالم الثقافية والأماكن السياحية',
    failedToSendMessage: 'فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    getInTouchTitle: 'تواصل معنا',
    contactDescription: 'هل لديك أسئلة أو تحتاج مساعدة؟ نحن هنا للمساعدة! تواصل معنا عبر أي من القنوات التالية.',
    sendUsMessage: 'أرسل لنا رسالة',
    messageSentSuccessfully: 'تم إرسال الرسالة بنجاح!',
    thankYouContact: 'شكراً لتواصلك معنا. سنرد خلال 24 ساعة.',
    bookingSubmittedSuccess: 'تم إرسال الحجز بنجاح!',
    bookYourTrip: 'احجز رحلتك',
    completeFormStartJourney: 'أكمل النموذج أدناه لبدء رحلتك',
    bookingType: 'نوع الحجز',
    yourDetails: 'بياناتك',
    destination: 'الوجهة',
    review: 'مراجعة',
    yearsExperience: 'سنوات الخبرة',
    happyTravelers: 'مسافرين سعداء',
    destinations: 'وجهات',
    storyText2: 'نتخصص في تقديم حلول سفر شاملة مصممة حسب احتياجاتكم.',
    storyText3: 'من الحجز إلى التخطيط، نوفر كل شيء لنجعل رحلتكم لا تُنسى.',
    customerFirst: 'العميل أولاً',
    customerFirstDesc: 'عملاؤنا في قلب كل ما نقوم به. نسعى لتجاوز التوقعات وإنشاء ذكريات تدوم.',
  },
  en: {
    // Navigation
    home: 'Home',
    aboutUs: 'About Us',
    aboutTitle: 'About Rainbow Travel',
    services: 'Services',
    offers: 'Offers',
    contact: 'Contact',
    loginSignup: 'Login / Sign Up',

    // Search
    searchPlaceholder: 'Search destinations, services, offers...',
    searchDestinations: 'Search destinations...',

    // Hero sections
    welcome: 'Welcome to Rainbow Travel',
    exploreWorld: 'Explore the World with Us',
    journeyBegins: 'Your Journey Begins...',
    memoriesYours: 'Memories Are Yours',
    yourTrustedPartner: 'Your trusted partner in Nablus, providing complete travel solutions and unforgettable experiences around the world.',
    discoverDestinations: 'Discover Amazing Destinations',
    topDestinations: 'Top Travel Destinations',
    explorePopular: 'Explore the most popular countries that people love to visit',
    ourServices: 'Our Services',
    completeSolutions: 'Complete travel solutions designed for your needs. From booking to planning, we provide everything.',
    specialOffers: 'Special Offers',
    offersPageDesc: 'Discover amazing travel offers and exclusive packages for your dream destinations',
    exclusiveDeals: 'Exclusive deals and packages for unforgettable experiences',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    getInTouch: 'We are here to help you plan your perfect trip. Get in touch today!',

    // Buttons and actions
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    bookNow: 'Book Now',
    viewDetails: 'View Details',
    sendMessage: 'Send Message',
    sending: 'Sending...',
    submit: 'Submit',

    // Forms
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    message: 'Message',
    name: 'Name',

    // Services
    flightBooking: 'Flight Booking',
    flightDesc: 'Book flights to destinations around the world with competitive prices and flexible options.',
    hotelReservations: 'Hotel Reservations',
    hotelDesc: 'Find and book the perfect accommodation for your trip.',
    tourPackages: 'Tour Packages',
    tourDesc: 'Explore carefully designed tour packages that include flights, hotels, tours, and activities.',
    visaAssistance: 'Visa Assistance',
    visaDesc: 'Get specialized help with visa applications and documentation.',
    travelPlanning: 'Travel Planning',
    planningDesc: 'Let our experienced travel consultants help you plan your perfect trip.',

    // Features
    internationalFlights: 'International & Domestic Flights',
    bestFare: 'Best Price Guarantee',
    easyCancellation: 'Easy Cancellation & Rescheduling',
    customerSupport: '24/7 Customer Support',
    wideAccommodations: 'Wide Range of Accommodations',
    bestPrice: 'Best Price Guarantee',
    verifiedReviews: 'Verified Reviews & Ratings',
    groupRates: 'Special Group Rates',
    allInclusive: 'All-Inclusive Packages',
    customizable: 'Customizable Itineraries',
    localGuides: 'Expert Local Guides',
    privateTours: 'Group & Private Tours',
    visaConsultation: 'Visa Consultations',
    documentPrep: 'Document Preparation',
    applicationTracking: 'Application Tracking',

    // Auth
    login: 'Login',
    signup: 'Sign Up',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    nameRequired: 'Full name is required',
    passwordsNotMatch: 'Passwords do not match',
    invalidEmail: 'Invalid email address',
    passwordTooShort: 'Password must be at least 6 characters',
    loginSuccess: 'Login successful',
    signupSuccess: 'Account created successfully',
    loginError: 'Login failed',
    signupError: 'Signup failed',
    welcomeBack: 'Welcome Back',
    loginToAccess: 'Login to access your account',
    createYourAccount: 'Create Your Account',
    joinAndExplore: 'Join us and start exploring the world',
    rememberMe: 'Remember me',
    loggingIn: 'Logging in...',
    signingUp: 'Signing up...',
    enterYourEmail: 'Enter your email',
    enterYourPassword: 'Enter your password',
    enterYourFullName: 'Enter your full name',
    createPassword: 'Create a password',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    iAgreeToThe: 'I agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    creatingAccount: 'Creating Account...',
    createAccount: 'Create Account',
    backToHome: 'Back to Home',
    loadingServices: 'Loading services...',
    whyChooseRainbow: 'Why Choose Rainbow Travel?',
    committedToExceptional: 'We are committed to providing exceptional travel experiences',
    bestValueMoney: 'We offer the best value for your money with exclusive deals and competitive prices.',
    professionalSupport: 'Our professional and friendly team is committed to providing outstanding customer service.',
    wellPlannedItineraries: 'All details are carefully planned and organized to ensure your trip is smooth, safe, and stress-free.',
    regularPromotions: 'We regularly update our offers to provide you with the best deals and latest destinations.',
    filterByCountry: 'Filter by Country',
    allCountries: 'All Countries',
    filterByPrice: 'Filter by Price',
    allPrices: 'All Prices',
    under700: 'Under $700',
    between700And1000: '$700 - $1000',
    over1000: 'Over $1000',
    showingResults: 'Showing {count} result{plural} for your search',
    loadingOffers: 'Loading offers...',
    reviews: 'reviews',
    packageIncludes: 'Package Includes',
    highlights: 'Highlights',
    exploreDestinations: 'Explore Destinations',
    popularTouristAttractions: 'Popular Tourist Attractions',
    discoverBeachesLandmarks: 'Discover beautiful beaches, landmarks, and cultural destinations',
    failedToSendMessage: 'Failed to send message. Please try again.',
    getInTouchTitle: 'Get in Touch',
    contactDescription: 'Have questions or need assistance? We are here to help! Reach out to us through any of the following channels.',
    sendUsMessage: 'Send Us a Message',
    messageSentSuccessfully: 'Message Sent Successfully!',
    thankYouContact: 'Thank you for contacting us. We will get back to you within 24 hours.',
    bookingSubmittedSuccess: 'Booking submitted successfully!',
    bookYourTrip: 'Book Your Trip',
    completeFormStartJourney: 'Complete the form below to start your journey',
    bookingType: 'Booking Type',
    yourDetails: 'Your Details',
    destination: 'Destination',
    review: 'Review',
    yearsExperience: 'Years Experience',
    happyTravelers: 'Happy Travelers',
    destinations: 'Destinations',
    storyText2: 'We specialize in providing comprehensive travel solutions designed for your needs.',
    storyText3: 'From booking to planning, we provide everything to make your journey unforgettable.',
    customerFirst: 'Customer First',
    customerFirstDesc: 'Our customers are at the heart of everything we do. We strive to exceed expectations and create lasting memories.',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    page: 'Page',
    of: 'of',

    // Footer and additional
    contactToday: 'Contact us today and let us help you plan your perfect vacation',
    readyToBook: 'Ready to book your trip?',
    contactCustom: 'Contact us and we\'ll create a custom package just for you',
    cantFind: 'Can\'t find what you\'re looking for?',
    'Showing {count} destinations matching your search': 'Showing {count} destinations matching your search',
    'View All Offers': 'View All Offers',
    'What Our Customers Say': 'What Our Customers Say',
    'Real experiences from happy travelers': 'Real experiences from happy travelers',
    'Ready to Start Your Journey?': 'Ready to Start Your Journey?',
    'Book your dream vacation today and create memories that last a lifetime': 'Book your dream vacation today and create memories that last a lifetime',
    'Contact Us': 'Contact Us',
    'Follow Us': 'Follow Us',
    'Rainbow Travel & Tourism': 'Rainbow Travel & Tourism',
    'All rights reserved.': 'All rights reserved.',
    'Have questions or need assistance? We are here to help! Reach out to us through any of the following channels.': 'Have questions or need assistance? We are here to help! Reach out to us through any of the following channels.',
    'Find Us on the Map': 'Find Us on the Map',
    'Visit our office at Nablus City Center': 'Visit our office at Nablus City Center',
    'Office Hours': 'Office Hours',
    'Sunday - Thursday': 'Sunday - Thursday',
    'Saturday': 'Saturday',
    'Emergency support available 24/7 by phone': 'Emergency support available 24/7 by phone',
    'Get in Touch': 'Get in Touch',
    'Send Us a Message': 'Send Us a Message',
    'Message Sent Successfully!': 'Message Sent Successfully!',
    'Thank you for contacting us. We will get back to you within 24 hours.': 'Thank you for contacting us. We will get back to you within 24 hours.',
    'Enter your email': 'Enter your email',

    // About page specific
    ourMissionText: 'To provide exceptional travel experiences through comprehensive, reliable, and affordable travel solutions. We strive to make every journey smooth and unforgettable, ensuring our customers return home with stories worth sharing and memories they\'ll cherish forever.',
    ourVisionText: 'To become the leading travel agency in Palestine, recognized for our commitment to excellence, innovation, and customer satisfaction. We envision a future where travel is accessible to all, and where Rainbow Travel is the first choice for travelers seeking quality and value.',
    whyChooseDesc: 'We\'re more than just a travel agency – we\'re your partners in adventure',
    ourCoreValues: 'Our Core Values',
  },
};

const fixedArabicTranslations: Record<string, string> = {
  home: 'الرئيسية',
  aboutUs: 'من نحن',
  aboutTitle: 'عن رينبو ترافل',
  services: 'الخدمات',
  ourServices: 'خدماتنا',
  faq: 'الأسئلة الشائعة',
  offers: 'العروض',
  contact: 'اتصل بنا',
  contactUs: 'اتصل بنا',
  loginSignup: 'تسجيل الدخول / إنشاء حساب',
  searchPlaceholder: 'ابحث عن الوجهات أو الخدمات أو العروض...',
  searchDestinations: 'ابحث عن الوجهات...',
  welcome: 'مرحبًا بكم في رينبو ترافل',
  exploreWorld: 'استكشف العالم معنا',
  journeyBegins: 'رحلتك تبدأ معنا...',
  memoriesYours: 'والذكريات لكم',
  yourTrustedPartner: 'شريككم الموثوق في نابلس، نقدم حلول سفر متكاملة وتجارب لا تنسى حول العالم.',
  discoverDestinations: 'اكتشف وجهات مذهلة',
  topDestinations: 'أفضل وجهات السفر',
  explorePopular: 'استكشف أكثر الدول شعبية التي يحب الناس زيارتها',
  completeSolutions: 'حلول سفر متكاملة مصممة حسب احتياجاتك. من الحجز إلى التخطيط، نوفر لك كل شيء.',
  specialOffers: 'عروض خاصة',
  offersPageDesc: 'اكتشف عروض سفر رائعة وباقات حصرية لوجهات أحلامك',
  exclusiveDeals: 'عروض وباقات حصرية لتجارب لا تنسى',
  quickLinks: 'روابط سريعة',
  getInTouch: 'نحن هنا لمساعدتك في تخطيط رحلتك المثالية. تواصل معنا اليوم!',
  getStarted: 'ابدأ الآن',
  learnMore: 'اعرف المزيد',
  bookNow: 'احجز الآن',
  viewDetails: 'عرض التفاصيل',
  sendMessage: 'إرسال الرسالة',
  sending: 'جارٍ الإرسال...',
  submit: 'إرسال',
  fullName: 'الاسم الكامل',
  email: 'البريد الإلكتروني',
  phone: 'الهاتف',
  message: 'الرسالة',
  name: 'الاسم',
  login: 'تسجيل الدخول',
  signup: 'إنشاء حساب',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  forgotPassword: 'نسيت كلمة المرور؟',
  noAccount: 'ليس لديك حساب؟',
  haveAccount: 'لديك حساب بالفعل؟',
  createAccount: 'إنشاء حساب',
  emailRequired: 'البريد الإلكتروني مطلوب',
  passwordRequired: 'كلمة المرور مطلوبة',
  nameRequired: 'الاسم مطلوب',
  passwordsNotMatch: 'كلمات المرور غير متطابقة',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  passwordTooShort: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  loginSuccess: 'تم تسجيل الدخول بنجاح',
  signupSuccess: 'تم إنشاء الحساب بنجاح',
  loginError: 'فشل تسجيل الدخول',
  signupError: 'فشل إنشاء الحساب',
  welcomeBack: 'أهلًا بعودتك',
  loginToAccess: 'سجل الدخول للوصول إلى حسابك',
  createYourAccount: 'أنشئ حسابك',
  joinAndExplore: 'انضم إلينا وابدأ باستكشاف العالم',
  rememberMe: 'تذكرني',
  loggingIn: 'جارٍ تسجيل الدخول...',
  signingUp: 'جارٍ إنشاء الحساب...',
  enterYourEmail: 'أدخل بريدك الإلكتروني',
  enterYourPassword: 'أدخل كلمة المرور',
  enterYourFullName: 'أدخل اسمك الكامل',
  createPassword: 'أنشئ كلمة مرور',
  confirmYourPassword: 'أكد كلمة المرور',
  iAgreeToThe: 'أوافق على',
  termsOfService: 'شروط الخدمة',
  and: 'و',
  privacyPolicy: 'سياسة الخصوصية',
  creatingAccount: 'جارٍ إنشاء الحساب...',
  backToHome: 'العودة للرئيسية',
  loading: 'جارٍ التحميل...',
  error: 'خطأ',
  success: 'نجاح',
  close: 'إغلاق',
  yes: 'نعم',
  no: 'لا',
  cancel: 'إلغاء',
  save: 'حفظ',
  delete: 'حذف',
  edit: 'تعديل',
  view: 'عرض',
  back: 'رجوع',
  next: 'التالي',
  previous: 'السابق',
  page: 'صفحة',
  of: 'من',
  loadingServices: 'جارٍ تحميل الخدمات...',
  filterByCountry: 'تصفية حسب البلد',
  allCountries: 'جميع البلدان',
  filterByPrice: 'تصفية حسب السعر',
  allPrices: 'جميع الأسعار',
  under700: 'أقل من 700 دولار',
  between700And1000: '700 - 1000 دولار',
  over1000: 'أكثر من 1000 دولار',
  showingResults: 'عرض {count} نتيجة{plural} لبحثك',
  loadingOffers: 'جارٍ تحميل العروض...',
  reviews: 'تقييمات',
  packageIncludes: 'تشمل الباقة',
  highlights: 'النقاط البارزة',
  exploreDestinations: 'استكشف الوجهات',
  popularTouristAttractions: 'المعالم السياحية الشهيرة',
  discoverBeachesLandmarks: 'اكتشف الشواطئ الجميلة والمعالم الثقافية والأماكن السياحية',
  bookingSubmittedSuccess: 'تم إرسال الحجز بنجاح!',
  bookYourTrip: 'احجز رحلتك',
  completeFormStartJourney: 'أكمل النموذج أدناه لبدء رحلتك',
  bookingType: 'نوع الحجز',
  yourDetails: 'بياناتك',
  destination: 'الوجهة',
  destinations: 'الوجهات',
  review: 'مراجعة',
  yearsExperience: 'سنوات الخبرة',
  happyTravelers: 'مسافرون سعداء',
  'Contact Us': 'اتصل بنا',
  'Follow Us': 'تابعنا',
  'Rainbow Travel & Tourism': 'رينبو ترافل والسياحة',
  'All rights reserved.': 'جميع الحقوق محفوظة.',
  'View All Offers': 'عرض جميع العروض',
  'What Our Customers Say': 'ماذا يقول عملاؤنا',
  'Real experiences from happy travelers': 'تجارب حقيقية من مسافرين سعداء',
  'Ready to Start Your Journey?': 'هل أنت مستعد لبدء رحلتك؟',
  'Book your dream vacation today and create memories that last a lifetime': 'احجز عطلتك المثالية اليوم واصنع ذكريات تدوم مدى الحياة',
  heroKicker: 'حان وقت',
  heroTitleLine1: 'السفر',
  heroTitleLine2: 'والاستكشاف',
  heroSubtitle: 'العالم معنا!',
  letsGoTogether: 'هيا ننطلق معا',
  bringingTravel: 'نحول احلام السفر',
  dreamsToLife: 'الى حقيقة',
  journeyDesc: 'سافر معنا ضمن برامج مخصصة بالكامل، حيث الوجهات الجميلة والتجارب المختارة بعناية تصنع رحلتك المثالية.',
  chooseDestination: 'اختر الوجهة',
  chooseDestinationDesc: 'اختر من بين وجهات وفنادق وتجارب كثيرة لتجد الرحلة الانسب لك.',
  checkAvailability: 'تحقق من التوفر',
  checkAvailabilityDesc: 'نساعدك في اختيار المواعيد والباقات المتاحة حسب ميزانيتك ووقتك.',
  letsGo: 'انطلق معنا',
  letsGoDesc: 'بعد تأكيد التفاصيل، نجهز لك كل شيء لتبدأ رحلتك براحة.',
  homeCompanyKicker: 'مرحبا بكم في رينبو للسفر والسياحة',
  homeCompanyDesc: 'نقع في قلب نابلس - مركز مدينة نابلس، الطابق الثاني - ونحن وكالة سفركم الموثوقة لتقديم حلول سفر كاملة وصناعة تجارب لا تنسى. مع اسعار منافسة وخدمة ممتازة ورحلات منظمة وعروض مستمرة، نجعل عطلتكم التي تحلمون بها حقيقة.',
  exploreDestinationsLabel: 'استكشف الوجهات',
  popularDestinations: 'وجهات شهيرة',
  dragExplore: 'اسحب لاستكشاف وجهات رائعة حول العالم',
  tours: 'جولات',
  Dubai: 'دبي',
  Egypt: 'مصر',
  France: 'فرنسا',
  Italy: 'ايطاليا',
  Maldives: 'المالديف',
  'Saudi Arabia': 'السعودية',
  Turkey: 'تركيا',
  luxuryDesertCity: 'مدينة فاخرة في الصحراء',
  ancientWonders: 'عجائب تاريخية',
  cityOfLights: 'مدينة الانوار',
  romanticGetaway: 'رحلة رومانسية',
  tropicalParadise: 'جنة استوائية',
  culturalHeritage: 'تراث ثقافي',
  eastMeetsWest: 'حيث يلتقي الشرق بالغرب',
  peopleJoined: 'اكثر من 50 شخص انضموا',
  travelStatsTitle: 'احصائيات سفر تنبض بالحياة.',
  travelStatsDesc: 'استكشف تجارب سفر مميزة بتصميم شفاف يجمع الحركة والعمق والتأثيرات الناعمة فوق الخلفية.',
  experienceWorld: 'اكتشف العالم',
  naturalFreedom: 'حرية طبيعية',
  inspiringJourneys: 'رحلات ملهمة',
  topDestinationsMarquee: 'افضل الوجهات',
  exploreNow: 'استكشف الآن',
  exploreYourWay: 'استكشف بطريقتك',
  viewOffer: 'عرض العرض',
  leaveComment: 'اترك تعليقا',
  yourComments: 'تعليقك',
  yourName: 'اسمك',
  city: 'المدينة',
  commentAdded: 'تمت اضافة التعليق بنجاح!',
  dontMissDeals: 'لا تفوت عروض السفر المميزة لدينا',
  viewAllOffers: 'عرض جميع العروض',
  companyNameLine1: 'رينبو ترافل',
  companyNameLine2: 'والسياحة',
  adminAccess: 'دخول الإدارة',
  preparingDashboard: 'جاري تجهيز لوحة التحكم',
  loadingTravelControlCenter: 'جاري تحميل مركز إدارة السفر...',
  emailAddressLabel: 'البريد الإلكتروني',
  emailShortPlaceholder: 'your@email.com',
  hidePassword: 'إخفاء كلمة المرور',
  showPassword: 'إظهار كلمة المرور',
  signingIn: 'جاري تسجيل الدخول...',
  signIn: 'تسجيل الدخول',
  beachDestinationAlt: 'وجهة شاطئية',
  mountainTravelSceneAlt: 'مشهد سفر جبلي',
  winterTravelSceneAlt: 'مشهد سفر شتوي',
  contactFormSubject: 'رسالة نموذج التواصل',
  failedToSendMessage: 'تعذر إرسال الرسالة. يرجى المحاولة مرة أخرى.',
  sendUsMessage: 'أرسل لنا رسالة',
  contactPlanTitle: 'دعنا نخطط شيئا لا ينسى.',
  contactPlanDesc: 'شاركنا أفكار سفرك وسنحولها إلى خطة سلسة ومخصصة بلمسة مميزة.',
  enterYourName: 'أدخل اسمك',
  emailPlaceholder: 'your.email@example.com',
  contactMessagePlaceholder: 'أخبرنا عن خطط سفرك أو اسألنا أي سؤال...',
  messageSentSuccessfully: 'تم إرسال الرسالة بنجاح!',
  thankYouContact: 'شكرا لتواصلك معنا. سنرد عليك خلال 24 ساعة.',
  visitUs: 'زورونا',
  findOurOffice: 'اعثر على مكتبنا',
  contactOfficeIntro: 'نقع في قلب مركز مدينة نابلس، مكتبنا سهل الوصول وجاهز لاستقبالكم.',
  officeLocationMap: 'خريطة موقع المكتب',
  address: 'العنوان',
  callUs: 'اتصل بنا',
  emailUs: 'راسلنا',
  contactAddressContent: 'مركز مدينة نابلس\nالطابق الثاني\nنابلس، فلسطين',
  contactPhoneContent: '0597441666\nدعم 24/7',
  contactEmailContent: 'info@rainbowtravel.ps\nالرد: خلال 24 ساعة',
  getDirections: 'احصل على الاتجاهات',
  amazingPackagesAvailable: '{count} باقات رائعة متاحة',
  offersGridDesc: 'اضغط على أي عرض لعرض التفاصيل الكاملة وحجز عطلتك المثالية اليوم',
  off: 'خصم',
  reviewsCount: '{count} تقييم',
  limitedTimeOffer: 'عرض لفترة محدودة',
  premiumDestination: 'وجهة مميزة',
  ratingOutOfFive: 'تقييم {rating}/5',
  happyTravelersCount: '{count} مسافر سعيد',
  perfectFor: 'مثالي لـ {value}',
  askQuestions: 'اسألنا',
  whyOffersStandOut: 'لماذا تتميز عروضنا',
  premiumQuality: 'جودة مميزة',
  premiumQualityDesc: 'وجهات مختارة بعناية وتجارب سفر فاخرة',
  unbeatablePrices: 'أسعار لا تقاوم',
  unbeatablePricesDesc: 'أفضل الأسعار بشفافية كاملة وبدون رسوم مخفية',
  completeProtection: 'حماية كاملة',
  completeProtectionDesc: 'تأمين سفر ودعم 24/7 ضمن الخدمة',
  istanbulTurkey: 'إسطنبول، تركيا',
  aqabaJordan: 'العقبة، الأردن',
  sharmEgypt: 'شرم الشيخ، مصر',
  dubaiUae: 'دبي، الإمارات',
  cairoEgypt: 'القاهرة، مصر',
  maleMaldives: 'ماليه، المالديف',
  sixDaysFiveNights: '6 أيام / 5 ليالي',
  sevenDaysSixNights: '7 أيام / 6 ليالي',
  dubaiLuxuryExperience: 'تجربة دبي الفاخرة',
  cairoPyramidsExplorer: 'استكشاف القاهرة والأهرامات',
  maldivesParadiseRetreat: 'منتجع جنة المالديف',
  offerIstanbulDesc: 'اختبر سحر إسطنبول حيث يلتقي الشرق بالغرب. استكشف المعالم التاريخية، واستمتع برحلة في البوسفور، وانغمس في الثقافة والمذاق التركي في واحدة من أجمل مدن العالم.',
  offerAqabaDesc: 'اكتشف جمال العقبة بمياه البحر الأحمر الصافية، ومواقع الغوص العالمية، وخيارات مغامرات الصحراء. مثالية لمحبي الشواطئ والرياضات المائية.',
  offerSharmDesc: 'استمتع بالفخامة في واحدة من أجمل وجهات المنتجعات عالميا. باقة شاملة تقدم شواطئ نقية، وغوصا مميزا، ومنتجعات صحية، وترفيها عالميا.',
  offerDubaiDesc: 'اختبر قمة الفخامة الحديثة في دبي، من ناطحات السحاب المذهلة إلى رحلات السفاري الذهبية والتسوق العالمي والمطاعم الراقية.',
  offerCairoDesc: 'اكتشف أسرار مصر القديمة مع زيارة الأهرامات العظيمة وأبو الهول وكنوز المتحف المصري، واستمتع بثقافة القاهرة الأصيلة على ضفاف النيل.',
  offerMaldivesDesc: 'اهرب إلى جنة المالديف مع الفلل فوق الماء والشواطئ البيضاء والمياه الفيروزية الصافية. مثالية لشهر العسل والاسترخاء والمغامرات البحرية.',
  includeHotelBreakfast: 'إقامة فندقية مع الإفطار',
  includeAirportTransfers: 'تنقلات المطار عند الوصول والمغادرة',
  includeHagiaSophiaTours: 'جولات إرشادية إلى آيا صوفيا',
  includeSultanAhmedMosque: 'زيارة مسجد السلطان أحمد',
  includeBosphorusCruise: 'جولة بحرية في البوسفور',
  includeProfessionalGuide: 'مرشد سياحي محترف',
  includeBeachfrontHotel: 'إقامة فندقية على الشاطئ',
  includeSeaActivities: 'أنشطة بحرية مثل السنوركلينغ',
  includeInternalTransportation: 'مواصلات داخلية',
  includeWadiRumTrip: 'رحلة اختيارية إلى وادي رم',
  includeRedSeaDiving: 'فرص غوص في البحر الأحمر',
  includeBeachEquipment: 'استئجار معدات الشاطئ',
  includeFiveStarResort: 'منتجع خمس نجوم شامل',
  includeUnlimitedMeals: 'وجبات ومشروبات غير محدودة',
  includeSwimmingPools: 'عدة مسابح',
  includeEntertainmentActivities: 'ترفيه وأنشطة',
  includeBeachWaterSports: 'دخول الشاطئ ورياضات مائية',
  includeSpaAccess: 'دخول مرافق السبا',
  includeFiveStarHotel: 'إقامة في فندق خمس نجوم',
  includeBurjKhalifa: 'زيارة برج خليفة الطابق 148',
  includeDesertSafari: 'سفاري صحراوي مع عشاء BBQ',
  includeDubaiMarina: 'رحلة بحرية في دبي مارينا',
  includeShoppingTours: 'جولات مراكز التسوق',
  includeCityTourGuide: 'جولة في المدينة مع مرشد',
  includeHotelNearPyramids: 'فندق بالقرب من الأهرامات',
  includePyramidsSphinxTour: 'جولة الأهرامات وأبو الهول',
  includeEgyptianMuseum: 'زيارة المتحف المصري',
  includeNileDinner: 'عشاء على نهر النيل',
  includeEgyptianMeals: 'وجبات مصرية تقليدية',
  includeEntranceFees: 'جميع رسوم الدخول مشمولة',
  includeOverwaterVilla: 'فيلا فاخرة فوق الماء',
  includeAllInclusiveMeals: 'وجبات ومشروبات شاملة',
  includeWaterSportsEquipment: 'معدات الرياضات المائية',
  includeSnorkelingDiving: 'سنوركلينغ وغوص',
  includeSpaTreatments: 'جلسات سبا مشمولة',
  includePrivateBeach: 'دخول شاطئ خاص',
  highlightHistoricLandmarks: 'معالم تاريخية',
  highlightCulturalExperiences: 'تجارب ثقافية',
  highlightTurkishCuisine: 'مذاق تركي لذيذ',
  highlightGrandBazaar: 'التسوق في البازار الكبير',
  highlightCrystalWaters: 'مياه صافية كالكريستال',
  highlightCoralReefs: 'استكشاف الشعاب المرجانية',
  highlightDesertAdventure: 'خيار مغامرة صحراوية',
  highlightWaterSports: 'أنشطة الرياضات المائية',
  highlightLuxuryAccommodation: 'إقامة فاخرة',
  highlightAllInclusive: 'تجربة شاملة',
  highlightRedSeaBeaches: 'شواطئ البحر الأحمر',
  highlightEveningEntertainment: 'ترفيه مسائي',
  highlightModernArchitecture: 'عمارة حديثة',
  highlightLuxuryShopping: 'تسوق فاخر',
  highlightDesertAdventures: 'مغامرات صحراوية',
  highlightWorldClassDining: 'مطاعم عالمية',
  highlightAncientWonders: 'عجائب قديمة',
  highlightHistoricalTreasures: 'كنوز تاريخية',
  highlightNileExperience: 'تجربة النيل',
  highlightEgyptianCulture: 'ثقافة مصرية',
  highlightOverwaterBungalows: 'أكواخ فوق الماء',
  highlightPristineBeaches: 'شواطئ نقية',
  highlightMarineLife: 'استكشاف الحياة البحرية',
  highlightUltimateRelaxation: 'استرخاء كامل',
  cultureLovers: 'محبي الثقافة',
  beachAdventure: 'الشاطئ والمغامرة',
  luxurySeekers: 'محبي الفخامة',
  modernLuxury: 'الفخامة الحديثة',
  historyEnthusiasts: 'محبي التاريخ',
  honeymooners: 'شهر العسل',
  popular: 'الأكثر شعبية',
  bestValue: 'أفضل قيمة',
  bestRated: 'الأعلى تقييما',
  premium: 'فاخر',
  historic: 'تاريخي',
  paradise: 'جنة',
  questionsAndAnswers: 'الأسئلة والأجوبة',
  faqHeroDesc: 'اعثر على إجابات لأسئلة السفر الخاصة بك',
  faqBookingCategory: 'الحجز',
  faqCustomizationCategory: 'التخصيص',
  faqServicesCategory: 'الخدمات',
  faqPaymentsCategory: 'الدفع',
  faqSupportCategory: 'الدعم',
  faqTransfersCategory: 'النقل',
  faqBookTripQuestion: 'كيف أحجز رحلة؟',
  faqBookTripAnswer: 'اختر وجهة أو جولة، أرسل نموذج الحجز، وسيقوم فريقنا بتأكيد التفاصيل معك.',
  faqCustomizeQuestion: 'هل يمكنني تخصيص برنامج رحلتي؟',
  faqCustomizeAnswer: 'نعم. يمكننا تنسيق الطيران والفنادق والجولات والتنقلات حسب ميزانيتك وأسلوب سفرك.',
  faqGroupTravelQuestion: 'هل تقدمون دعما لسفر المجموعات؟',
  faqGroupTravelAnswer: 'بالتأكيد. نتولى رحلات المجموعات بتخطيط وتنسيق مخصص.',
  faqPaymentQuestion: 'ما طرق الدفع المقبولة؟',
  faqPaymentAnswer: 'تعتمد خيارات الدفع على نوع الحجز، وسنشاركها معك أثناء تأكيد التفاصيل.',
  faqSupportQuestion: 'كيف يمكنني التواصل مع الدعم؟',
  faqSupportAnswer: 'يمكنك التواصل معنا عبر صفحة الاتصال أو الهاتف أو البريد الإلكتروني في أي وقت.',
  faqTransfersQuestion: 'هل توفرون خدمة الاستقبال والتوصيل من المطار؟',
  faqTransfersAnswer: 'نعم. يمكننا ترتيب التنقلات من وإلى المطار أو خدمات الاستقبال الخاصة حسب تفاصيل رحلتك.',
  stillHaveQuestions: 'هل لديك أسئلة أخرى؟',
  faqCtaDesc: 'فريق الدعم جاهز لمساعدتك في تخطيط رحلتك المثالية. تواصل معنا في أي وقت.',
  contactSupport: 'تواصل مع الدعم',
  servicesHeroDesc: 'خدمات سفر مصممة لتكون رحلتك أسهل',
  ourPremiumServices: 'خدماتنا المميزة',
  servicesPremiumDesc: 'حلول سفر متكاملة مصممة حسب احتياجاتك',
  servicesFlightDesc: 'احجز رحلتك بسهولة مع أفضل شركات الطيران المحلية والعالمية. نضمن لك أسعارا منافسة وخيارات مرنة ودعما كاملا في كل خطوة.',
  servicesHotelDesc: 'استمتع بإقامات فاخرة أو اقتصادية في أفضل الفنادق حول العالم. نساعدك في اختيار الفندق الأنسب لاحتياجاتك مع عروض حصرية وتقييمات موثوقة.',
  servicesTourDesc: 'اكتشف العالم مع باقات سياحية شاملة تغطي الطيران والإقامة والجولات والأنشطة، مع برامج مخصصة تناسب اهتماماتك.',
  visaServices: 'خدمات التأشيرات',
  servicesVisaDesc: 'تعامل مع متطلبات التأشيرة بسهولة من خلال استشاراتنا المتخصصة. نساعدك في الوثائق والطلبات لضمان تجربة سلسة.',
  servicesInsuranceDesc: 'احم استثمارك مع تأمين سفر شامل يغطي الحالات الطبية الطارئة وإلغاء الرحلات وفقدان الأمتعة حول العالم.',
  servicesGroupDesc: 'استمتع بمغامرات لا تنسى مع باقات سفر المجموعات. نتولى الترتيبات كاملة لرحلات منظمة وخصومات خاصة.',
  internationalDomesticBookings: 'حجوزات دولية ومحلية',
  bestPriceGuarantee: 'ضمان أفضل سعر',
  easyCancellationChanges: 'إلغاء وتعديل بسهولة',
  support247: 'دعم على مدار الساعة',
  diverseAccommodationOptions: 'خيارات إقامة متنوعة',
  exclusiveDealsPrices: 'عروض وأسعار حصرية',
  verifiedGuestReviews: 'تقييمات ضيوف موثوقة',
  groupDiscounts: 'خصومات للمجموعات',
  allInclusivePackages: 'باقات شاملة',
  flexibleCustomPrograms: 'برامج مرنة ومخصصة',
  professionalLocalGuides: 'مرشدون محليون محترفون',
  groupPrivateTours: 'جولات جماعية وخاصة',
  visaConsultationGuidance: 'استشارة وإرشاد للتأشيرات',
  documentPreparationAssistance: 'مساعدة في تجهيز الوثائق',
  fastTrackProcessing: 'معالجة سريعة',
  multiCountryExpertise: 'خبرة في عدة دول',
  fullMedicalCoverage: 'تغطية طبية كاملة',
  tripCancellationProtection: 'حماية عند إلغاء الرحلة',
  baggageDelayCoverage: 'تغطية الأمتعة والتأخير',
  emergencyAssistance247: 'مساعدة طارئة 24/7',
  customizedGroupItineraries: 'برامج مخصصة للمجموعات',
  specialGroupRatesDiscounts: 'أسعار وخصومات خاصة للمجموعات',
  dedicatedGroupCoordinator: 'منسق خاص للمجموعة',
  teamBuildingTravelExperiences: 'تجارب سفر لبناء الفريق',
  features: 'المميزات',
  whyCompetitivePricesDesc: 'أفضل قيمة مقابل مالك مع عروض حصرية',
  whyExcellentServiceDesc: 'دعم عملاء احترافي وودود',
  whyOrganizedTripsDesc: 'برامج منظمة لرحلة مريحة بدون توتر',
  whyContinuousOffersDesc: 'عروض مستمرة وخصومات خاصة',
  servicesCtaDesc: 'تواصل معنا اليوم ودعنا نساعدك في تخطيط عطلتك المثالية',
  destinationHeroDesc: 'اكتشف رحلات لا تنسى مصممة خصيصا لك.',
  turkeyTopDestinations: 'أبرز الوجهات: إسطنبول، أنطاليا، طرابزون',
  egyptTopDestinations: 'أبرز الوجهات: القاهرة، شرم الشيخ',
  jordanTopDestinations: 'أبرز الوجهات: العقبة، عمّان',
  turkeyAttractionDesc: 'استمتع بالغنى الثقافي والسواحل الجميلة في تركيا. اسحب الفيديوهات لمشاهدة لمحات من كل منطقة.',
  egyptAttractionDesc: 'من أهرامات القاهرة إلى شواطئ شرم الشيخ، تجمع مصر بين التاريخ والشمس في رحلة واحدة.',
  jordanAttractionDesc: 'اكتشف ساحل البحر الأحمر في الأردن والمواقع التاريخية من خلال لمحات سريعة في الأعلى.',
  marqueeDiscover: 'اكتشف',
  marqueeExplore: 'استكشف',
  marqueePlanTrip: 'خطط رحلتك',
  marqueeCuratedDestinations: 'وجهات مختارة',
  searchPlaceholderShort: 'ابحث...',
  filter: 'تصفية',
  toursRange: 'الجولات 0 - 10',
  clearFilters: 'مسح الفلاتر',
  filterByToursCount: 'تصفية حسب {count} جولات',
  tour: 'جولة',
  noDestinationsFound: 'لا توجد وجهات مطابقة',
  istanbulPackage: 'باقة إسطنبول',
  aqabaBeachTrip: 'رحلة شاطئ العقبة',
  sharmElSheikhLuxury: 'شرم الشيخ الفاخرة',
  Jordan: 'الأردن',
  Amman: 'عمّان',
  Cairo: 'القاهرة',
  'Hong Kong': 'هونغ كونغ',
  Jerusalem: 'القدس',
  Tokyo: 'طوكيو',
  Istanbul: 'إسطنبول',
  Antalya: 'أنطاليا',
  Trabzon: 'طرابزون',
  'Sharm El Sheikh': 'شرم الشيخ',
  Aqaba: 'العقبة',
  Nablus: 'نابلس',
  Ramallah: 'رام الله',
  Jenin: 'جنين',
  fiveDaysFourNights: '5 أيام / 4 ليالي',
  fourDaysThreeNights: '4 أيام / 3 ليالي',
  testimonialTurkey: 'رينبو ترافل جعلت رحلتنا إلى تركيا لا تنسى! كل شيء كان منظما بشكل ممتاز من الطيران إلى حجز الفندق. أنصح بها جدا!',
  testimonialDubai: 'أفضل وكالة سفر في فلسطين! الفريق محترف ومتعاون، ورحلتنا إلى دبي كانت رائعة بفضل خدمتهم الممتازة.',
  testimonialDeals: 'أسعار منافسة وعروض ممتازة! رينبو ترافل ساعدتنا نلاقي الباقة المناسبة ضمن ميزانيتنا. سنحجز معهم مرة أخرى بالتأكيد!',
  testimonialLina: 'شغل رائع يا لينا من نابلس! كل شيء مرتب ونظيف ومبدع.',
  testimonialSarah: 'عمل جميل يا سارة من رام الله! التصميم جميل ومنظم جدا.',
  testimonialMaya: 'مبهر جدا يا مايا من جنين! واضح الجهد والاهتمام بالتفاصيل.',
  flightBooking: 'حجز الطيران',
  hotelReservations: 'حجز الفنادق',
  tourPackages: 'باقات الرحلات',
  visaAssistance: 'مساعدة التأشيرات',
  travelPlanning: 'تخطيط السفر',
  aboutHeroSubtitle: 'اعرفنا أكثر وخطط رحلتك بثقة',
  travelDestinationAlt: 'وجهة سفر',
  adventureExperienceAlt: 'تجربة مغامرة',
  culturalTourAlt: 'جولة ثقافية',
  planYourTrip: 'خطط رحلتك',
  withUs: 'معنا',
  aboutPlanningDesc: 'نساعدك في بناء رحلة مريحة ومناسبة لاحتياجاتك، من اختيار الوجهة إلى ترتيب التفاصيل، حتى تبدأ رحلتك بثقة وراحة.',
  exclusiveTrip: 'رحلة مميزة',
  exclusiveTripDesc: 'نختار لك برامج سفر مدروسة وتجارب تناسب ذوقك وميزانيتك.',
  professionalGuide: 'إرشاد احترافي',
  professionalGuideDesc: 'فريقنا يتابع معك التفاصيل ويقدم لك الدعم قبل الرحلة وأثناءها.',
  aboutStoryMain: 'تأسست رينبو ترافل والسياحة برؤية واضحة: أن نجعل السفر أسهل وأكثر متعة وذكرى جميلة لكل مسافر. من قلب نابلس في مركز مدينة نابلس، الطابق الثاني، أصبحنا اسما موثوقا في خدمات السفر والسياحة.',
  aboutStorySecond: 'بدأت رحلتنا بشغف الاستكشاف والالتزام بالجودة. وعلى مدار السنوات ساعدنا آلاف المسافرين على اكتشاف العالم وصناعة ذكريات تدوم.',
  ourTeam: 'فريقنا',
  teamTitle: 'الأشخاص خلف كل رحلة',
  teamDesc: 'يجمع فريقنا بين معرفة الوجهات، دقة التخطيط، والدعم الودود لتبقى كل رحلة سلسة من البداية للنهاية.',
  teamLeadName: 'ربيع عليوي',
  teamLeadRole: 'المدير',
  teamLeadNote: 'يقود رؤية الشركة ورسالتها في تقديم تجارب سفر استثنائية.',
  aboutMarqueeText: 'استكشف العالم معنا • استكشف العالم معنا • استكشف العالم معنا',
  coreValuesDesc: 'المبادئ التي توجه كل قرار وكل خدمة نقدمها',
  trustReliability: 'الثقة والاعتمادية',
  trustReliabilityDesc: 'نبني كل رحلة على تواصل واضح وخدمة يعتمد عليها ووعود نلتزم بها.',
  continuousImprovement: 'تطوير مستمر',
  continuousImprovementDesc: 'نطور خدماتنا وشراكاتنا وطريقة التخطيط باستمرار لنقدم تجارب سفر أسهل وأفضل.',
  aboutCtaDesc: 'اصنع ذكريات لا تنسى مع رينبو ترافل.',
  groupTravel: 'سفر المجموعات',
};

const fixedEnglishTranslations: Record<string, string> = {
  heroKicker: "IT'S TIME TO",
  heroTitleLine1: 'TRAVEL',
  heroTitleLine2: 'EXPLORE',
  heroSubtitle: 'THE WORLD WITH US!',
  letsGoTogether: "Let's Go Together",
  bringingTravel: 'Bringing Your Travel',
  dreamsToLife: 'Dreams To Life',
  journeyDesc: 'Journey with us on fully customized itineraries through beautiful destinations, carefully chosen experiences, and memorable travel moments.',
  chooseDestination: 'Choose Destination',
  chooseDestinationDesc: 'Choose from destinations, hotels, and experiences to find the trip that fits you best.',
  checkAvailability: 'Check Availability',
  checkAvailabilityDesc: 'We help you select available dates and packages based on your budget and timing.',
  letsGo: "Let's Go",
  letsGoDesc: 'Once the details are confirmed, we prepare everything so your journey starts smoothly.',
  homeCompanyKicker: 'WELCOME TO RAINBOW TRAVEL & TOURISM',
  homeCompanyDesc: 'Located in the heart of Nablus - Nablus City Center, second floor - we are your trusted travel agency dedicated to providing complete travel solutions and creating memorable experiences. With competitive prices, excellent service, organized trips, and continuous offers, we make your dream vacation a reality.',
  exploreDestinationsLabel: 'EXPLORE DESTINATIONS',
  popularDestinations: 'Popular Destinations',
  dragExplore: 'Drag to explore amazing destinations around the world',
  tours: 'Tours',
  Dubai: 'Dubai',
  Egypt: 'Egypt',
  France: 'France',
  Italy: 'Italy',
  Maldives: 'Maldives',
  'Saudi Arabia': 'Saudi Arabia',
  Turkey: 'Turkey',
  luxuryDesertCity: 'Luxury Desert City',
  ancientWonders: 'Ancient Wonders',
  cityOfLights: 'City of Lights',
  romanticGetaway: 'Romantic Getaway',
  tropicalParadise: 'Tropical Paradise',
  culturalHeritage: 'Cultural Heritage',
  eastMeetsWest: 'Where East Meets West',
  peopleJoined: '50+ People Joined',
  travelStatsTitle: 'Travel stats that feel alive.',
  travelStatsDesc: 'Explore premium travel experiences with a glass-style showcase that blends motion, depth, and soft fade effects over the background.',
  experienceWorld: 'EXPERIENCE THE WORLD',
  naturalFreedom: 'NATURAL FREEDOM',
  inspiringJourneys: 'INSPIRING JOURNEYS',
  topDestinationsMarquee: 'TOP DESTINATIONS',
  exploreNow: 'EXPLORE NOW',
  exploreYourWay: 'Explore Your Way',
  viewOffer: 'View Offer',
  leaveComment: 'Leave a comment',
  yourComments: 'Your comments',
  yourName: 'Your name',
  city: 'City',
  commentAdded: 'Comment added successfully!',
  dontMissDeals: "Don't miss out on our amazing travel deals",
  viewAllOffers: 'View All Offers',
  companyNameLine1: 'Rainbow Travel',
  companyNameLine2: '& Tourism',
  adminAccess: 'Admin Access',
  preparingDashboard: 'Preparing dashboard',
  loadingTravelControlCenter: 'Loading your travel control center...',
  emailAddressLabel: 'Email Address',
  emailShortPlaceholder: 'your@email.com',
  hidePassword: 'Hide password',
  showPassword: 'Show password',
  signingIn: 'Signing in...',
  signIn: 'Sign In',
  beachDestinationAlt: 'Beach destination',
  mountainTravelSceneAlt: 'Mountain travel scene',
  winterTravelSceneAlt: 'Winter travel scene',
  contactFormSubject: 'Contact Form Message',
  failedToSendMessage: 'Failed to send message. Please try again.',
  sendUsMessage: 'Send Us a Message',
  contactPlanTitle: "Let's plan something unforgettable.",
  contactPlanDesc: "Share your travel ideas and we'll turn them into a smooth, tailored plan with a premium touch.",
  enterYourName: 'Enter your name',
  emailPlaceholder: 'your.email@example.com',
  contactMessagePlaceholder: 'Tell us about your travel plans or ask us any questions...',
  messageSentSuccessfully: 'Message Sent Successfully!',
  thankYouContact: 'Thank you for contacting us. We will get back to you within 24 hours.',
  visitUs: 'Visit Us',
  findOurOffice: 'Find Our Office',
  contactOfficeIntro: 'Located in the heart of Nablus City Center, our office is easily accessible and ready to welcome you.',
  officeLocationMap: 'Office Location Map',
  address: 'Address',
  callUs: 'Call Us',
  emailUs: 'Email Us',
  contactAddressContent: 'Nablus City Center\nSecond Floor\nNablus, Palestine',
  contactPhoneContent: '0597441666\n24/7 Support',
  contactEmailContent: 'info@rainbowtravel.ps\nResponse: Within 24h',
  getDirections: 'Get Directions',
  amazingPackagesAvailable: '{count} Amazing Packages Available',
  offersGridDesc: 'Click on any offer to view complete details and book your dream vacation today',
  off: 'OFF',
  reviewsCount: '{count} reviews',
  limitedTimeOffer: 'LIMITED TIME OFFER',
  premiumDestination: 'Premium Destination',
  ratingOutOfFive: '{rating}/5 Rating',
  happyTravelersCount: '{count} Happy Travelers',
  perfectFor: 'Perfect for {value}',
  askQuestions: 'Ask Questions',
  whyOffersStandOut: 'Why Our Offers Stand Out',
  premiumQuality: 'Premium Quality',
  premiumQualityDesc: 'Hand-picked destinations & luxury experiences',
  unbeatablePrices: 'Unbeatable Prices',
  unbeatablePricesDesc: 'Best rates with full transparency, no hidden fees',
  completeProtection: 'Complete Protection',
  completeProtectionDesc: 'Travel insurance & 24/7 support included',
  istanbulTurkey: 'Istanbul, Turkey',
  aqabaJordan: 'Aqaba, Jordan',
  sharmEgypt: 'Sharm El Sheikh, Egypt',
  dubaiUae: 'Dubai, UAE',
  cairoEgypt: 'Cairo, Egypt',
  maleMaldives: 'Male, Maldives',
  sixDaysFiveNights: '6 Days / 5 Nights',
  sevenDaysSixNights: '7 Days / 6 Nights',
  dubaiLuxuryExperience: 'Dubai Luxury Experience',
  cairoPyramidsExplorer: 'Cairo & Pyramids Explorer',
  maldivesParadiseRetreat: 'Maldives Paradise Retreat',
  offerIstanbulDesc: "Experience the magic of Istanbul where East meets West. Explore historic landmarks, enjoy a Bosphorus cruise, and immerse yourself in Turkish culture and cuisine at one of the world's most captivating cities.",
  offerAqabaDesc: 'Discover the breathtaking beauty of Aqaba with pristine red sea waters, world-class diving spots, and optional desert adventures. Perfect for beach lovers and water sports enthusiasts seeking unforgettable aquatic experiences.',
  offerSharmDesc: "Indulge in ultimate luxury at one of the world's premier resort destinations. This all-inclusive package offers pristine beaches, championship diving, spa retreats, and world-class entertainment for the ultimate getaway.",
  offerDubaiDesc: 'Experience the epitome of modern luxury in Dubai. From breathtaking skyscrapers to golden desert safaris, world-class shopping to exquisite dining, Dubai offers an unforgettable blend of contemporary luxury and Arabian adventure.',
  offerCairoDesc: 'Uncover the mysteries of ancient Egypt with exclusive access to the Great Pyramids, the enigmatic Sphinx, and the treasures of the Egyptian Museum. Experience authentic Cairo culture along the legendary Nile River.',
  offerMaldivesDesc: 'Escape to paradise in the Maldives with overwater bungalows, pristine white-sand beaches, and crystal-clear turquoise waters. Perfect for honeymooners and those seeking ultimate relaxation, romance, and marine adventures.',
  includeHotelBreakfast: 'Hotel accommodation with breakfast',
  includeAirportTransfers: 'Airport transfers (arrival & departure)',
  includeHagiaSophiaTours: 'Guided tours to Hagia Sophia',
  includeSultanAhmedMosque: 'Visit to Sultan Ahmed Mosque',
  includeBosphorusCruise: 'Bosphorus cruise tour',
  includeProfessionalGuide: 'Professional tour guide',
  includeBeachfrontHotel: 'Beachfront hotel stay',
  includeSeaActivities: 'Sea activities (snorkeling)',
  includeInternalTransportation: 'Internal transportation',
  includeWadiRumTrip: 'Optional Wadi Rum desert trip',
  includeRedSeaDiving: 'Red Sea diving opportunities',
  includeBeachEquipment: 'Beach equipment rental',
  includeFiveStarResort: '5-star all-inclusive resort',
  includeUnlimitedMeals: 'Unlimited meals & drinks',
  includeSwimmingPools: 'Multiple swimming pools',
  includeEntertainmentActivities: 'Entertainment & activities',
  includeBeachWaterSports: 'Beach access & water sports',
  includeSpaAccess: 'Spa facilities access',
  includeFiveStarHotel: '5-star hotel accommodation',
  includeBurjKhalifa: 'Burj Khalifa visit (148th floor)',
  includeDesertSafari: 'Desert safari with BBQ dinner',
  includeDubaiMarina: 'Dubai Marina cruise',
  includeShoppingTours: 'Shopping mall tours',
  includeCityTourGuide: 'City tour with guide',
  includeHotelNearPyramids: 'Hotel near pyramids',
  includePyramidsSphinxTour: 'Guided Pyramids & Sphinx tour',
  includeEgyptianMuseum: 'Egyptian Museum visit',
  includeNileDinner: 'Nile River cruise dinner',
  includeEgyptianMeals: 'Traditional Egyptian meals',
  includeEntranceFees: 'All entrance fees included',
  includeOverwaterVilla: 'Luxury overwater villa',
  includeAllInclusiveMeals: 'All-inclusive meals & drinks',
  includeWaterSportsEquipment: 'Water sports equipment',
  includeSnorkelingDiving: 'Snorkeling & diving',
  includeSpaTreatments: 'Spa treatments included',
  includePrivateBeach: 'Private beach access',
  highlightHistoricLandmarks: 'Historic landmarks',
  highlightCulturalExperiences: 'Cultural experiences',
  highlightTurkishCuisine: 'Delicious Turkish cuisine',
  highlightGrandBazaar: 'Shopping at Grand Bazaar',
  highlightCrystalWaters: 'Crystal clear waters',
  highlightCoralReefs: 'Coral reefs exploration',
  highlightDesertAdventure: 'Desert adventure option',
  highlightWaterSports: 'Water sports activities',
  highlightLuxuryAccommodation: 'Luxury accommodation',
  highlightAllInclusive: 'All-inclusive experience',
  highlightRedSeaBeaches: 'Red Sea beaches',
  highlightEveningEntertainment: 'Evening entertainment',
  highlightModernArchitecture: 'Modern architecture',
  highlightLuxuryShopping: 'Luxury shopping',
  highlightDesertAdventures: 'Desert adventures',
  highlightWorldClassDining: 'World-class dining',
  highlightAncientWonders: 'Ancient wonders',
  highlightHistoricalTreasures: 'Historical treasures',
  highlightNileExperience: 'Nile experience',
  highlightEgyptianCulture: 'Egyptian culture',
  highlightOverwaterBungalows: 'Overwater bungalows',
  highlightPristineBeaches: 'Pristine beaches',
  highlightMarineLife: 'Marine life exploration',
  highlightUltimateRelaxation: 'Ultimate relaxation',
  cultureLovers: 'Culture Lovers',
  beachAdventure: 'Beach & Adventure',
  luxurySeekers: 'Luxury Seekers',
  modernLuxury: 'Modern Luxury',
  historyEnthusiasts: 'History Enthusiasts',
  honeymooners: 'Honeymooners',
  popular: 'Popular',
  bestValue: 'Best Value',
  bestRated: 'Best Rated',
  premium: 'Premium',
  historic: 'Historic',
  paradise: 'Paradise',
  questionsAndAnswers: 'Questions and Answers',
  faqHeroDesc: 'Find answers to your travel questions',
  faqBookingCategory: 'Booking',
  faqCustomizationCategory: 'Customization',
  faqServicesCategory: 'Services',
  faqPaymentsCategory: 'Payments',
  faqSupportCategory: 'Support',
  faqTransfersCategory: 'Transfers',
  faqBookTripQuestion: 'How do I book a trip?',
  faqBookTripAnswer: 'Choose a destination or tour, submit the booking form, and our team will confirm the details with you.',
  faqCustomizeQuestion: 'Can I customize my itinerary?',
  faqCustomizeAnswer: 'Yes. We can tailor flights, hotels, tours, and transfers around your budget and travel style.',
  faqGroupTravelQuestion: 'Do you offer group travel support?',
  faqGroupTravelAnswer: 'Absolutely. We handle group trips with dedicated planning and coordination.',
  faqPaymentQuestion: 'What payment methods are accepted?',
  faqPaymentAnswer: 'Payment options depend on your booking and will be shared during confirmation.',
  faqSupportQuestion: 'How can I contact support?',
  faqSupportAnswer: 'You can reach us through the contact page, by phone, or by email anytime.',
  faqTransfersQuestion: 'Do you offer airport pickup and drop-off?',
  faqTransfersAnswer: 'Yes. We can arrange airport transfers and private pickup or drop-off services based on your trip details.',
  stillHaveQuestions: 'Still have questions?',
  faqCtaDesc: 'Our support team is ready to help you plan the perfect journey. Reach out anytime.',
  contactSupport: 'Contact Support',
  servicesHeroDesc: 'Travel services designed to feel effortless',
  ourPremiumServices: 'Our Premium Services',
  servicesPremiumDesc: 'Comprehensive travel solutions tailored to your needs',
  servicesFlightDesc: 'Book your flight easily with top international and local airlines. We guarantee competitive prices, flexible options, and full support at every step.',
  servicesHotelDesc: 'Enjoy luxury or budget stays at the best hotels worldwide. We help you choose the perfect hotel for your needs with exclusive offers and trusted reviews.',
  servicesTourDesc: 'Discover the world with all-inclusive tour packages covering flights, accommodation, tours, and activities. We offer tailor-made programs to suit your interests.',
  visaServices: 'Visa Services',
  servicesVisaDesc: 'Navigate visa requirements effortlessly with our expert consultation services. We handle documentation and applications to ensure a smooth experience.',
  servicesInsuranceDesc: 'Protect your investment with comprehensive travel insurance covering medical emergencies, trip cancellations, and lost luggage worldwide.',
  servicesGroupDesc: 'Experience unforgettable adventures with our specialized group travel packages. We handle all arrangements for organized itineraries and exclusive group discounts.',
  internationalDomesticBookings: 'International & domestic bookings',
  bestPriceGuarantee: 'Best price guarantee',
  easyCancellationChanges: 'Easy cancellation & changes',
  support247: '24/7 support',
  diverseAccommodationOptions: 'Diverse accommodation options',
  exclusiveDealsPrices: 'Exclusive deals & prices',
  verifiedGuestReviews: 'Verified guest reviews',
  groupDiscounts: 'Group discounts',
  allInclusivePackages: 'All-inclusive packages',
  flexibleCustomPrograms: 'Flexible & custom programs',
  professionalLocalGuides: 'Professional local guides',
  groupPrivateTours: 'Group & private tours',
  visaConsultationGuidance: 'Visa consultation & guidance',
  documentPreparationAssistance: 'Document preparation assistance',
  fastTrackProcessing: 'Fast-track processing',
  multiCountryExpertise: 'Multi-country expertise',
  fullMedicalCoverage: 'Full medical coverage',
  tripCancellationProtection: 'Trip cancellation protection',
  baggageDelayCoverage: 'Baggage & delay coverage',
  emergencyAssistance247: '24/7 emergency assistance',
  customizedGroupItineraries: 'Customized group itineraries',
  specialGroupRatesDiscounts: 'Special group rates & discounts',
  dedicatedGroupCoordinator: 'Dedicated group coordinator',
  teamBuildingTravelExperiences: 'Team building travel experiences',
  features: 'Features',
  whyCompetitivePricesDesc: 'Best value for your money with exclusive deals',
  whyExcellentServiceDesc: 'Professional and friendly customer support',
  whyOrganizedTripsDesc: 'Well-planned itineraries for stress-free travel',
  whyContinuousOffersDesc: 'Regular promotions and special discounts',
  servicesCtaDesc: 'Contact us today and let us help you plan your perfect vacation',
  destinationHeroDesc: 'Discover unforgettable trips tailored just for you.',
  turkeyTopDestinations: 'Top destinations: Istanbul, Antalya, Trabzon',
  egyptTopDestinations: 'Top: Cairo, Sharm El Sheikh',
  jordanTopDestinations: 'Top: Aqaba, Amman',
  turkeyAttractionDesc: 'Experience the cultural richness and stunning coastlines of Turkey. Swipe the videos to preview highlights from each region.',
  egyptAttractionDesc: 'From the pyramids of Cairo to the beaches of Sharm El Sheikh, Egypt offers history and sun in one trip.',
  jordanAttractionDesc: "Dive into Jordan's Red Sea coast and ancient sites through quick previews above.",
  marqueeDiscover: 'DISCOVER',
  marqueeExplore: 'EXPLORE',
  marqueePlanTrip: 'PLAN YOUR TRIP',
  marqueeCuratedDestinations: 'CURATED DESTINATIONS',
  searchPlaceholderShort: 'Search...',
  filter: 'Filter',
  toursRange: 'Tours 0 - 10',
  clearFilters: 'Clear filters',
  filterByToursCount: 'Filter by {count} tours',
  tour: 'Tour',
  noDestinationsFound: 'No destinations found',
  istanbulPackage: 'Istanbul Package',
  aqabaBeachTrip: 'Aqaba Beach Trip',
  sharmElSheikhLuxury: 'Sharm El Sheikh Luxury',
  Jordan: 'Jordan',
  Amman: 'Amman',
  Cairo: 'Cairo',
  'Hong Kong': 'Hong Kong',
  Jerusalem: 'Jerusalem',
  Tokyo: 'Tokyo',
  Istanbul: 'Istanbul',
  Antalya: 'Antalya',
  Trabzon: 'Trabzon',
  'Sharm El Sheikh': 'Sharm El Sheikh',
  Aqaba: 'Aqaba',
  Nablus: 'Nablus',
  Ramallah: 'Ramallah',
  Jenin: 'Jenin',
  fiveDaysFourNights: '5 Days / 4 Nights',
  fourDaysThreeNights: '4 Days / 3 Nights',
  testimonialTurkey: 'Rainbow Travel made our trip to Turkey unforgettable! Everything was perfectly organized, from flights to hotel bookings. Highly recommended!',
  testimonialDubai: 'Best travel agency in Palestine! The staff is professional and helpful. Our Dubai vacation was amazing thanks to their excellent service.',
  testimonialDeals: 'Competitive prices and excellent deals! Rainbow Travel helped us find the perfect package within our budget. Will definitely book again!',
  testimonialLina: 'Amazing work, Lina from Nablus! Everything looks clean and creative.',
  testimonialSarah: 'Great job, Sarah from Ramallah! The design is beautiful and very organized.',
  testimonialMaya: 'Really impressive, Maya from Jenin! You can clearly see the effort and attention to detail.',
  aboutHeroSubtitle: 'Know Us Better, Plan Your Journey Wisely',
  travelDestinationAlt: 'Travel destination',
  adventureExperienceAlt: 'Adventure experience',
  culturalTourAlt: 'Cultural tour',
  planYourTrip: 'Plan Your Trip',
  withUs: 'With Us',
  aboutPlanningDesc: 'We help you shape a comfortable trip around your needs, from choosing the destination to arranging the details, so your journey starts with confidence.',
  exclusiveTrip: 'Exclusive Trip',
  exclusiveTripDesc: 'We select thoughtful travel programs and experiences that match your style and budget.',
  professionalGuide: 'Professional Guide',
  professionalGuideDesc: 'Our team follows the details with you and provides support before and during your trip.',
  aboutStoryMain: 'Rainbow Travel & Tourism was founded with a clear vision: to make travel easier, more enjoyable, and memorable for every traveler. Located in the heart of Nablus at Nablus City Center, second floor, we have become a trusted name in travel and tourism services.',
  aboutStorySecond: 'Our journey began with a passion for exploration and a commitment to quality. Over the years, we have helped thousands of travelers discover the world and create memories that last.',
  ourTeam: 'Our Team',
  teamTitle: 'The people behind the journey',
  teamDesc: 'Our team blends destination knowledge, planning discipline, and friendly support to keep every trip smooth from start to finish.',
  teamLeadName: 'Rabee Aliwi',
  teamLeadRole: 'Director',
  teamLeadNote: 'Leads the company vision and mission of exceptional travel experiences.',
  aboutMarqueeText: 'EXPLORE THE WORLD WITH US • EXPLORE THE WORLD WITH US • EXPLORE THE WORLD WITH US',
  coreValuesDesc: 'The principles that guide every decision and action we take',
  trustReliability: 'Trust & Reliability',
  trustReliabilityDesc: 'We build every trip on clear communication, dependable service, and promises our travelers can count on.',
  continuousImprovement: 'Continuous Improvement',
  continuousImprovementDesc: 'We keep improving our services, partnerships, and planning process to deliver smoother travel experiences.',
  aboutCtaDesc: 'Create unforgettable memories with Rainbow Travel.',
  groupTravel: 'Group Travel',
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get saved language from localStorage or default to English
    const saved = localStorage.getItem('rainbow-travel-language');
    return (saved === 'en' || saved === 'ar') ? saved : 'en';
  });

  const isRTL = false;
  const dir: 'rtl' | 'ltr' = 'ltr';

  // Keep layout direction fixed while allowing translated text to change.
  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    document.body.dir = dir;
    document.body.classList.remove('rtl');
    localStorage.setItem('rainbow-travel-language', language);
  }, [language, dir]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const dictionary = translations[language] as Record<string, string>;
    const fixedDictionary = language === 'ar' ? fixedArabicTranslations : fixedEnglishTranslations;
    let text = fixedDictionary[key] || dictionary[key] || key;

    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramValue));
      });
    }

    return text;
  };

  const textAlign = (align: 'left' | 'right' | 'center'): string => {
    if (align === 'center') return 'text-center';
    return align === 'left' ? 'text-left' : 'text-right';
  };

  const flexDirection = (direction: 'row' | 'col' = 'row'): string => {
    if (direction === 'col') return 'flex-col';
    return 'flex-row';
  };

  return (
    <LanguageContext.Provider value={{
      language,
      isRTL,
      t,
      dir,
      textAlign,
      flexDirection,
      toggleLanguage,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}
